version = 1

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "11"

[[transformers]]
name = "isort"
enabled = true

[[transformers]]
name = "google-java-format"
enabled = true
